### PR TITLE
added support to tap condition to know if the alert was tapped or no (ti...

### PR DESCRIPTION
**Pull request by paulocoutinhox**
...meout)

### CODE REVIEW

**Comment by radutzan** [comment]
Please read the documentation. OLGAV already has a `dismissible` property which allows dismissal with a tap. It can be set from an init method or independently.

**Comment by radutzan** [comment]
Sorry, I didn't read the code carefully the first time. I get that you're trying to capture whether OLGAV was dismissed with a tap or not, and though that might be useful, I don't think this is the best way to do it. I'll look into it the next time I work on OLGAV.

**Comment by paulocoutinhox** [comment]
Yes.
I know that completion method was executed everytime that is dismissed, but i know know the method that dismiss the alert (timeout or tap). This is essential, because every alert that i see, have different behavior when timeout and when was tapped. This is a UP to your control that im using it and added this behavior and is working great.

Thanks.

**Comment by radutzan** [comment]
I get that it's useful for you and you're free to use your fork, but adding a parameter to the `completionBlock` that has no contextual purpose other than passing an internal flag would break existing implementations and make little semantic sense. Also, duplicating the `-hide` code in a new public (!) method adds an unnecessary maintainability burden, again, just to pass this one internal flag. There's probably a better way to do this, which I'll consider on the next update.

**Comment by paulocoutinhox** [comment]
Ok.
I agree. I do it running only to make it work. After you update i will use yours.
Ty.

**Pull request closed without merging**
