### PR TITLE
Adding a Podspec

### PR DESCRIPTION
**Pull request by stigi**
Let me know if you have questions about that.

I already added it to the global pod spec directory at CocoaPods/Specs@a7daebf34

### CODE REVIEW

**Comment by radutzan** [comment]
We already have a Podspec, right here: https://github.com/ondalabs/OLGhostAlertView/blob/master/OLGhostAlertView.podspec

What am I missing?

**Comment by stigi** [comment]
Uh, wondering what I've been missing.... Now I'm confused..

Sorry. Will close the PR.

**Comment by stigi** [comment]
I updated the podspec in the global spec repo to your version:
CocoaPods/Specs@f0a2f7d733df019e056766857bd3b5ef387a5bc9

Sorry for the confusion :bow:

**Comment by radutzan** [comment]
No worries! Thanks anyway.

**Pull request closed without merging**
